title: Pin and socket jumper wires
hero_image: images/banner.png
description: A description of pin and socket jumper wires
version: 4
listed: false
copyedit: false
last_tested: "2022-02-04"
steps:
  - title: Pin and socket jumper wires
