title: Pin and socket jumper wires
hero_image: images/banner.png
description: pin-socket-jumper-wires description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-04"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
