---
title: Καλώδια με pin και socket jumper
hero_image: images/banner.png
description: Περιγραφή των καλωδίων pin και socket jumper
version: 4
listed: false
copyedit: false
last_tested: "2022-02-04"
steps:
  - title: Καλώδια με pin και socket jumper
